CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (
        tipo IN ('delivery', 'encomenda')
    ),
    descricao TEXT,
    ordem INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    categoria_id BIGINT NOT NULL
        REFERENCES categories(id),

    nome TEXT NOT NULL,
    descricao TEXT,

    tipo_preco TEXT NOT NULL CHECK (
        tipo_preco IN ('fixo', 'configuravel')
    ),

    preco_base INTEGER,
    preco_promocional INTEGER,

    imagem_url TEXT,

    disponivel BOOLEAN NOT NULL DEFAULT TRUE,
    destaque BOOLEAN NOT NULL DEFAULT FALSE,

    ordem INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE IF NOT EXISTS product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL
        REFERENCES products(id),

    nome TEXT NOT NULL,

    preco_base INTEGER NOT NULL,

    serve_pessoas INTEGER,

    disponivel BOOLEAN NOT NULL DEFAULT TRUE,

    ordem INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE IF NOT EXISTS option_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL
        REFERENCES products(id),

    nome TEXT NOT NULL,

    obrigatorio BOOLEAN NOT NULL DEFAULT TRUE,

    ordem INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE IF NOT EXISTS options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    option_group_id BIGINT NOT NULL
        REFERENCES option_groups(id),

    nome TEXT NOT NULL,

    preco_adicional INTEGER NOT NULL DEFAULT 0,

    requer_orcamento BOOLEAN NOT NULL DEFAULT FALSE,

    disponivel BOOLEAN NOT NULL DEFAULT TRUE,

    ordem INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE IF NOT EXISTS store_info (
    chave TEXT PRIMARY KEY,
    valor TEXT NOT NULL
);